version: 2
updates:
- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "weekly"
  open-pull-requests-limit: 5
  ignore:
  - dependency-name: "*"
    update-types:
    - "version-update:semver-major"
  - dependency-name: "scipy"
    versions: [">=1.18"]
  - dependency-name: "numpy"
    versions: [">=2.5"]
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  open-pull-requests-limit: 5
  ignore:
  - dependency-name: "*"
    update-types:
    - "version-update:semver-major"
