#!/usr/bin/env python3
"""Fail-closed CC0 native auto-merge classifier for this repository."""

from __future__ import annotations

import argparse
import base64
import binascii
import json
import os
import posixpath
import re
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path
from typing import Any


API_BASE = "https://api.github.com"
EXPECTED_REPOSITORY = "QuantStrategyLab/CryptoLivePoolPipelines"
EXPECTED_DEFAULT_BRANCH = "main"
EXPECTED_WORKFLOW_ID = 253773518
EXPECTED_WORKFLOW_NAME = "CI"
EXPECTED_WORKFLOW_PATH = ".github/workflows/ci.yml"
EXPECTED_RULESET_ID = 18235043
EXPECTED_CHECK = {"context": "test", "app_id": 15368, "app_slug": "github-actions"}
EXPECTED_ACTIVE_RULE = {
    "type": "required_status_checks",
    "ruleset_source_type": "Repository",
    "ruleset_source": EXPECTED_REPOSITORY,
    "ruleset_id": EXPECTED_RULESET_ID,
    "parameters": {
        "strict_required_status_checks_policy": True,
        "do_not_enforce_on_create": False,
        "required_status_checks": [{"context": "test", "integration_id": 15368}],
    },
}
ALLOWED_RUN_ACTOR = {"login": "quantcrossrepoautomation[bot]", "type": "Bot"}
ALLOWED_PR_AUTHOR = {"login": "quantcrossrepoautomation", "type": "Bot"}
ALLOWED_BRANCH_PREFIX = "codex/monthly-review-issue-"
ALLOWED_DOC_SUFFIXES = {".adoc", ".asciidoc", ".markdown", ".md", ".rst", ".txt"}
FORBIDDEN_DOC_COMPONENTS = {"_generated", "autogenerated", "data", "generated"}
GENERATED_MARKERS = ("@generated", "auto-generated", "autogenerated", "do not edit")
SHA_PATTERN = re.compile(r"^[0-9a-f]{40}$")


class GitHubApiError(RuntimeError):
    pass


def _reject(reason: str) -> dict[str, Any]:
    return {"eligible": False, "reason": reason}


def _valid_sha(value: object) -> bool:
    return isinstance(value, str) and SHA_PATTERN.fullmatch(value) is not None


def _allowed_path(path: object) -> bool:
    if not isinstance(path, str) or not path or path != path.strip():
        return False
    if "\\" in path or path.startswith("/") or posixpath.normpath(path) != path:
        return False
    if path in {"README.md", "README.zh-CN.md"}:
        return True
    parts = path.split("/")
    return (
        len(parts) > 1
        and parts[0] == "docs"
        and not any(part.casefold() in FORBIDDEN_DOC_COMPONENTS for part in parts)
        and Path(path).suffix.casefold() in ALLOWED_DOC_SUFFIXES
    )


def _regular_utf8_text(file_info: dict[str, Any]) -> bool:
    content = file_info["content"]
    if not isinstance(content, dict):
        return False
    if content.get("type") != "file" or content.get("encoding") != "base64":
        return False
    if content.get("submodule_git_url") is not None or content.get("target") is not None:
        return False
    if content.get("path") != file_info["path"] or content.get("sha") != file_info["sha"]:
        return False
    encoded = content.get("content")
    size = content.get("size")
    if not isinstance(encoded, str) or not isinstance(size, int) or size < 0:
        return False
    try:
        raw = base64.b64decode("".join(encoded.split()), validate=True)
        text = raw.decode("utf-8")
    except (binascii.Error, UnicodeDecodeError):
        return False
    if len(raw) != size or any(ord(char) < 32 and char not in "\n\r\t" for char in text):
        return False
    prefix = text[:4096].casefold()
    return not any(marker in prefix for marker in GENERATED_MARKERS)


def classify(context: dict[str, Any]) -> dict[str, Any]:
    """Return an allow/reject decision; malformed or unknown input is rejected."""
    try:
        repository = context["repository"]
        run = context["workflow_run"]
        pr = context["pull_request"]
        files = context["files"]

        if (
            repository["name_with_owner"] != EXPECTED_REPOSITORY
            or repository["is_fork"] is not False
            or repository["default_branch"] != EXPECTED_DEFAULT_BRANCH
            or repository["auto_merge_allowed"] is not True
            or repository["squash_merge_allowed"] is not True
        ):
            return _reject("repository_contract_mismatch")

        protection = repository["protection"]
        if (
            protection["pattern"] != EXPECTED_DEFAULT_BRANCH
            or protection["requires_status_checks"] is not True
            or protection["requires_strict_status_checks"] is not True
            or protection["requires_conversation_resolution"] is not True
            or protection["required_status_checks"] != [EXPECTED_CHECK]
            or repository["active_rules"] != [EXPECTED_ACTIVE_RULE]
        ):
            return _reject("strict_ci_policy_mismatch")

        if (
            run["action"] != "completed"
            or run["workflow_id"] != EXPECTED_WORKFLOW_ID
            or run["name"] != EXPECTED_WORKFLOW_NAME
            or run["path"] != EXPECTED_WORKFLOW_PATH
            or run["event"] != "pull_request"
            or run["status"] != "completed"
            or run["conclusion"] != "success"
        ):
            return _reject("trusted_ci_mismatch")
        if (
            run["repository"] != EXPECTED_REPOSITORY
            or run["repository_is_fork"] is not False
            or run["head_repository"] != EXPECTED_REPOSITORY
            or run["head_repository_is_fork"] is not False
            or {"login": run["actor_login"], "type": run["actor_type"]} != ALLOWED_RUN_ACTOR
            or {"login": run["triggering_actor_login"], "type": run["triggering_actor_type"]}
            != ALLOWED_RUN_ACTOR
        ):
            return _reject("bot_identity_mismatch")

        run_prs = run["pull_requests"]
        if not isinstance(run_prs, list) or len(run_prs) != 1:
            return _reject("pull_request_identity_mismatch")
        run_pr = run_prs[0]
        if (
            not isinstance(run_pr, dict)
            or run_pr["number"] != pr["number"]
            or run_pr["head_ref"] != run["head_branch"]
            or run_pr["head_sha"] != run["head_sha"]
            or run_pr["base_ref"] != EXPECTED_DEFAULT_BRANCH
            or run_pr["base_sha"] != pr["base_oid"]
        ):
            return _reject("pull_request_identity_mismatch")

        if (
            pr["state"] != "OPEN"
            or pr["is_draft"] is not False
            or {"login": pr["author_login"], "type": pr["author_type"]} != ALLOWED_PR_AUTHOR
            or pr["base_ref"] != EXPECTED_DEFAULT_BRANCH
            or pr["base_repository"] != EXPECTED_REPOSITORY
            or pr["base_repository_is_fork"] is not False
            or pr["head_repository"] != EXPECTED_REPOSITORY
            or pr["head_repository_is_fork"] is not False
            or pr["is_cross_repository"] is not False
            or not pr["head_ref"].startswith(ALLOWED_BRANCH_PREFIX)
            or pr["head_ref"] != run["head_branch"]
            or pr["head_oid"] != run["head_sha"]
            or not _valid_sha(pr["head_oid"])
            or pr["base_oid"] != repository["default_branch_oid"]
            or not _valid_sha(pr["base_oid"])
        ):
            return _reject("pull_request_identity_mismatch")

        if (
            pr["mergeable"] != "MERGEABLE"
            or pr["merge_state_status"] != "CLEAN"
            or pr["auto_merge_request"] is not None
        ):
            return _reject("merge_state_not_clear")
        if (
            pr["review_threads_complete"] is not True
            or not isinstance(pr["review_threads"], list)
            or any(thread.get("is_resolved") is not True for thread in pr["review_threads"])
        ):
            return _reject("review_state_not_clear")

        if (
            not isinstance(files, list)
            or not files
            or not isinstance(pr["changed_files"], int)
            or pr["changed_files"] != len(files)
        ):
            return _reject("file_set_not_cc0")
        for file_info in files:
            if not isinstance(file_info, dict):
                return _reject("file_set_not_cc0")
            counts = (file_info["additions"], file_info["deletions"], file_info["changes"])
            if (
                file_info["status"] not in {"added", "modified"}
                or file_info["previous_path"] is not None
                or not _allowed_path(file_info["path"])
                or not _valid_sha(file_info["sha"])
                or not all(isinstance(value, int) and value >= 0 for value in counts)
                or file_info["changes"] != file_info["additions"] + file_info["deletions"]
                or not _regular_utf8_text(file_info)
            ):
                return _reject("file_set_not_cc0")

        return {
            "eligible": True,
            "reason": "eligible_cc0",
            "pr_number": pr["number"],
            "head_sha": pr["head_oid"],
        }
    except (AttributeError, KeyError, TypeError, ValueError):
        return _reject("unknown_or_invalid_metadata")


class GitHubApi:
    def __init__(self, token: str) -> None:
        self._token = token

    def request(self, path: str, payload: dict[str, Any] | None = None) -> Any:
        url = path if path.startswith("https://") else f"{API_BASE}{path}"
        data = json.dumps(payload).encode("utf-8") if payload is not None else None
        headers = {
            "Authorization": f"Bearer {self._token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
            "User-Agent": "cryptolive-cc0-native-auto-merge",
        }
        request = urllib.request.Request(url, data=data, method="POST" if data else "GET", headers=headers)
        try:
            with urllib.request.urlopen(request, timeout=30) as response:
                return json.loads(response.read().decode("utf-8"))
        except (OSError, UnicodeDecodeError, json.JSONDecodeError, urllib.error.HTTPError) as exc:
            raise GitHubApiError("GitHub API metadata unavailable") from exc

    def graphql(self, query: str, variables: dict[str, Any]) -> dict[str, Any]:
        response = self.request("/graphql", {"query": query, "variables": variables})
        if not isinstance(response, dict) or response.get("errors") or not isinstance(response.get("data"), dict):
            raise GitHubApiError("GitHub GraphQL metadata unavailable")
        return response["data"]


REPOSITORY_QUERY = """
query($owner:String!,$name:String!,$number:Int!){
  repository(owner:$owner,name:$name){
    nameWithOwner isFork autoMergeAllowed squashMergeAllowed
    defaultBranchRef{
      name target{oid}
      branchProtectionRule{
        pattern requiresStatusChecks requiresStrictStatusChecks requiresConversationResolution
        requiredStatusChecks{context app{databaseId slug}}
      }
    }
    pullRequest(number:$number){
      number state isDraft author{login __typename}
      baseRefName baseRefOid baseRepository{nameWithOwner isFork}
      headRefName headRefOid headRepository{nameWithOwner isFork}
      isCrossRepository mergeable mergeStateStatus autoMergeRequest{enabledAt} changedFiles
      reviewThreads(first:100){nodes{isResolved} pageInfo{hasNextPage endCursor}}
    }
  }
}
"""

REVIEW_THREADS_QUERY = """
query($owner:String!,$name:String!,$number:Int!,$after:String!){
  repository(owner:$owner,name:$name){
    pullRequest(number:$number){
      reviewThreads(first:100,after:$after){nodes{isResolved} pageInfo{hasNextPage endCursor}}
    }
  }
}
"""


def _normalize_threads(api: GitHubApi, pr: dict[str, Any], number: int) -> tuple[bool, list[dict[str, Any]]]:
    connection = pr["reviewThreads"]
    threads = list(connection["nodes"])
    page_info = connection["pageInfo"]
    pages = 1
    while page_info["hasNextPage"] is True:
        cursor = page_info["endCursor"]
        if not isinstance(cursor, str) or not cursor or pages >= 100:
            return False, threads
        data = api.graphql(
            REVIEW_THREADS_QUERY,
            {"owner": "QuantStrategyLab", "name": "CryptoLivePoolPipelines", "number": number, "after": cursor},
        )
        connection = data["repository"]["pullRequest"]["reviewThreads"]
        threads.extend(connection["nodes"])
        page_info = connection["pageInfo"]
        pages += 1
    return page_info["hasNextPage"] is False, threads


def _pull_files(api: GitHubApi, number: int, changed_files: int, head_sha: str) -> list[dict[str, Any]]:
    if changed_files < 1 or changed_files > 3000 or not _valid_sha(head_sha):
        return []
    files: list[dict[str, Any]] = []
    for page in range(1, 31):
        batch = api.request(f"/repos/{EXPECTED_REPOSITORY}/pulls/{number}/files?per_page=100&page={page}")
        if not isinstance(batch, list):
            raise GitHubApiError("GitHub pull request file metadata unavailable")
        files.extend(batch)
        if len(batch) < 100:
            break

    normalized: list[dict[str, Any]] = []
    for item in files:
        path = item.get("filename")
        content: dict[str, Any] = {}
        if _allowed_path(path) and item.get("status") in {"added", "modified"}:
            encoded_path = urllib.parse.quote(path, safe="/")
            encoded_ref = urllib.parse.quote(head_sha, safe="")
            response = api.request(
                f"/repos/{EXPECTED_REPOSITORY}/contents/{encoded_path}?ref={encoded_ref}"
            )
            if isinstance(response, dict):
                content = {
                    key: response.get(key)
                    for key in ("type", "encoding", "size", "content", "sha", "path", "submodule_git_url", "target")
                }
        normalized.append(
            {
                "path": path,
                "status": item.get("status"),
                "previous_path": item.get("previous_filename"),
                "additions": item.get("additions"),
                "deletions": item.get("deletions"),
                "changes": item.get("changes"),
                "sha": item.get("sha"),
                "content": content,
            }
        )
    return normalized


def collect_context(event: dict[str, Any], api: GitHubApi) -> dict[str, Any]:
    run = event["workflow_run"]
    event_prs = run["pull_requests"]
    if not isinstance(event_prs, list) or len(event_prs) != 1:
        raise GitHubApiError("Ambiguous workflow run pull request")
    number = event_prs[0]["number"]
    if not isinstance(number, int) or number < 1:
        raise GitHubApiError("Invalid pull request number")

    data = api.graphql(
        REPOSITORY_QUERY,
        {"owner": "QuantStrategyLab", "name": "CryptoLivePoolPipelines", "number": number},
    )
    repository = data["repository"]
    pr = repository["pullRequest"]
    if not isinstance(repository, dict) or not isinstance(pr, dict):
        raise GitHubApiError("Pull request metadata unavailable")
    threads_complete, threads = _normalize_threads(api, pr, number)
    protection = repository["defaultBranchRef"]["branchProtectionRule"]
    checks = protection["requiredStatusChecks"]
    active_rules = api.request(f"/repos/{EXPECTED_REPOSITORY}/rules/branches/{EXPECTED_DEFAULT_BRANCH}")

    normalized_event_prs = [
        {
            "number": item.get("number"),
            "head_ref": (item.get("head") or {}).get("ref"),
            "head_sha": (item.get("head") or {}).get("sha"),
            "base_ref": (item.get("base") or {}).get("ref"),
            "base_sha": (item.get("base") or {}).get("sha"),
        }
        for item in event_prs
    ]
    head_repository = run.get("head_repository") or {}
    run_repository = run.get("repository") or {}
    author = pr.get("author") or {}
    base_repository = pr.get("baseRepository") or {}
    pr_head_repository = pr.get("headRepository") or {}
    actor = run.get("actor") or {}
    triggering_actor = run.get("triggering_actor") or {}
    changed_files = pr["changedFiles"]

    return {
        "repository": {
            "name_with_owner": repository.get("nameWithOwner"),
            "is_fork": repository.get("isFork"),
            "default_branch": repository["defaultBranchRef"].get("name"),
            "default_branch_oid": (repository["defaultBranchRef"].get("target") or {}).get("oid"),
            "auto_merge_allowed": repository.get("autoMergeAllowed"),
            "squash_merge_allowed": repository.get("squashMergeAllowed"),
            "protection": {
                "pattern": protection.get("pattern"),
                "requires_status_checks": protection.get("requiresStatusChecks"),
                "requires_strict_status_checks": protection.get("requiresStrictStatusChecks"),
                "requires_conversation_resolution": protection.get("requiresConversationResolution"),
                "required_status_checks": [
                    {
                        "context": item.get("context"),
                        "app_id": (item.get("app") or {}).get("databaseId"),
                        "app_slug": (item.get("app") or {}).get("slug"),
                    }
                    for item in checks
                ],
            },
            "active_rules": active_rules,
        },
        "workflow_run": {
            "action": event.get("action"),
            "id": run.get("id"),
            "workflow_id": run.get("workflow_id"),
            "name": run.get("name"),
            "path": run.get("path"),
            "event": run.get("event"),
            "status": run.get("status"),
            "conclusion": run.get("conclusion"),
            "head_branch": run.get("head_branch"),
            "head_sha": run.get("head_sha"),
            "repository": run_repository.get("full_name"),
            "repository_is_fork": run_repository.get("fork"),
            "head_repository": head_repository.get("full_name"),
            "head_repository_is_fork": head_repository.get("fork"),
            "actor_login": actor.get("login"),
            "actor_type": actor.get("type"),
            "triggering_actor_login": triggering_actor.get("login"),
            "triggering_actor_type": triggering_actor.get("type"),
            "pull_requests": normalized_event_prs,
        },
        "pull_request": {
            "number": pr.get("number"),
            "state": pr.get("state"),
            "is_draft": pr.get("isDraft"),
            "author_login": author.get("login"),
            "author_type": author.get("__typename"),
            "base_ref": pr.get("baseRefName"),
            "base_oid": pr.get("baseRefOid"),
            "base_repository": base_repository.get("nameWithOwner"),
            "base_repository_is_fork": base_repository.get("isFork"),
            "head_ref": pr.get("headRefName"),
            "head_oid": pr.get("headRefOid"),
            "head_repository": pr_head_repository.get("nameWithOwner"),
            "head_repository_is_fork": pr_head_repository.get("isFork"),
            "is_cross_repository": pr.get("isCrossRepository"),
            "mergeable": pr.get("mergeable"),
            "merge_state_status": pr.get("mergeStateStatus"),
            "auto_merge_request": pr.get("autoMergeRequest"),
            "changed_files": changed_files,
            "review_threads_complete": threads_complete,
            "review_threads": [{"is_resolved": item.get("isResolved")} for item in threads],
        },
        "files": _pull_files(api, number, changed_files, pr.get("headRefOid")),
    }


def _publish_decision(decision: dict[str, Any]) -> None:
    output_path = os.environ.get("GITHUB_OUTPUT")
    if output_path:
        with open(output_path, "a", encoding="utf-8") as output:
            print(f"eligible={'true' if decision.get('eligible') is True else 'false'}", file=output)
            print(f"reason={decision.get('reason', 'unknown_or_invalid_metadata')}", file=output)
            if decision.get("eligible") is True:
                print(f"pr_number={decision['pr_number']}", file=output)
                print(f"head_sha={decision['head_sha']}", file=output)
    summary_path = os.environ.get("GITHUB_STEP_SUMMARY")
    if summary_path:
        with open(summary_path, "a", encoding="utf-8") as summary:
            summary.write("## CC0 native auto-merge pilot\n")
            summary.write(f"- Eligible: `{'yes' if decision.get('eligible') is True else 'no'}`\n")
            summary.write(f"- Reason: `{decision.get('reason', 'unknown_or_invalid_metadata')}`\n")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--event", type=Path, required=True)
    args = parser.parse_args()
    try:
        event = json.loads(args.event.read_text(encoding="utf-8"))
        token = os.environ["GITHUB_TOKEN"]
        decision = classify(collect_context(event, GitHubApi(token)))
    except (GitHubApiError, KeyError, OSError, UnicodeDecodeError, json.JSONDecodeError):
        decision = _reject("unknown_or_invalid_metadata")
    _publish_decision(decision)
    print(json.dumps({"eligible": decision["eligible"], "reason": decision["reason"]}, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
